# Generated by Django 4.2.9 on 2024-11-23 13:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parking",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("total_lots", models.IntegerField()),
                ("available_lots", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ParkingEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("EN", "Entrance"), ("EX", "Exit")], max_length=2
                    ),
                ),
                (
                    "parking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.parking",
                    ),
                ),
            ],
        ),
    ]
