# Generated by Django 4.2.9 on 2024-11-23 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_parking_parkingentry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parking",
            old_name="available_lots",
            new_name="occupied_lots",
        ),
    ]
