# Generated by Django 4.2.9 on 2024-11-23 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_rename_available_lots_parking_occupied_lots"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
