# Generated by Django 4.2.9 on 2024-11-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0005_parkingentry_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="parking",
            name="latitude",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="parking",
            name="longitude",
            field=models.CharField(default="0", max_length=100),
        ),
    ]
