# Generated by Django 4.2.9 on 2024-11-24 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0007_device"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="user",
        ),
    ]
