name: CI Backend - Test and Type Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  SECRET_KEY: 'sssshhh'

jobs:
  test:
    name: Run Tests and Type Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Install dependencies
        run: devbox shell && task deps

      - name: Run mypy
        run: devbox shell && task backend-tests
